// Generated from Typst's symbol definitions. Maps dotted symbol names to Unicode characters.
// Source: crates/typst-library/src/math/ and crates/typst-library/src/symbols/

export const SYMBOLS: Record<string, string> = {
  // Greek lowercase
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  rho: 'ρ',
  sigma: 'σ',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',

  // Greek uppercase
  Alpha: 'Α',
  Beta: 'Β',
  Gamma: 'Γ',
  Delta: 'Δ',
  Epsilon: 'Ε',
  Zeta: 'Ζ',
  Eta: 'Η',
  Theta: 'Θ',
  Iota: 'Ι',
  Kappa: 'Κ',
  Lambda: 'Λ',
  Mu: 'Μ',
  Nu: 'Ν',
  Xi: 'Ξ',
  Pi: 'Π',
  Rho: 'Ρ',
  Sigma: 'Σ',
  Tau: 'Τ',
  Upsilon: 'Υ',
  Phi: 'Φ',
  Chi: 'Χ',
  Psi: 'Ψ',
  Omega: 'Ω',

  // Greek variants
  'epsilon.alt': 'ϵ',
  'phi.alt': 'ϕ',
  'theta.alt': 'ϑ',
  'rho.alt': 'ϱ',
  'kappa.alt': 'ϰ',
  'pi.alt': 'ϖ',
  'sigma.alt': 'ς',

  // Basic math
  infinity: '∞',
  infty: '∞',
  partial: '∂',
  nabla: '∇',
  forall: '∀',
  exists: '∃',
  'exists.not': '∄',
  nothing: '∅',
  emptyset: '∅',

  // Number sets (double-struck)
  NN: 'ℕ',
  ZZ: 'ℤ',
  QQ: 'ℚ',
  RR: 'ℝ',
  CC: 'ℂ',
  FF: '𝔽',
  HH: 'ℍ',

  // Logic
  not: '¬',
  and: '∧',
  or: '∨',
  xor: '⊻',
  top: '⊤',
  bot: '⊥',
  models: '⊨',
  'models.not': '⊭',
  tack: '⊢',
  'tack.r': '⊢',
  'tack.l': '⊣',
  'tack.r.double': '⊨',

  // Set operations
  'in': '∈',
  'in.not': '∉',
  'in.rev': '∋',
  'in.rev.not': '∌',
  subset: '⊂',
  supset: '⊃',
  'subset.eq': '⊆',
  'supset.eq': '⊇',
  'subset.eq.not': '⊈',
  'supset.eq.not': '⊉',
  'subset.neq': '⊊',
  'supset.neq': '⊋',
  union: '∪',
  'union.big': '⋃',
  'union.sq': '⊎',
  'union.sq.big': '⨆',
  sect: '∩',
  'sect.big': '⋂',
  'sect.sq': '⊓',
  'sect.sq.big': '⨅',
  complement: '∁',

  // Arithmetic
  plus: '+',
  minus: '−',
  times: '×',
  div: '÷',
  'dot.op': '⋅',
  'dot.c': '∙',
  'dot.basic': '.',
  ast: '∗',
  star: '⋆',
  compose: '∘',
  'circle.plus': '⊕',
  'circle.minus': '⊖',
  'circle.times': '⊗',
  'circle.dot': '⊙',
  'circle.small': '◦',
  dagger: '†',
  ddagger: '‡',
  prime: '′',
  dprime: '″',
  tprime: '‴',
  backprime: '‵',

  // Relations - equality
  'eq.not': '≠',
  'eq.equiv': '≡',
  'eq.nequiv': '≢',
  'eq.prec': '⋞',
  'eq.succ': '⋟',
  'eq.def': '≝',
  'eq.quest': '≟',
  'eq.colon': '≔',
  approx: '≈',
  'approx.not': '≉',
  'approx.eq': '≊',
  sim: '∼',
  'sim.eq': '≃',
  'sim.equiv': '≅',
  'sim.not': '≁',
  tilde: '∼',
  'tilde.eq': '≃',
  'tilde.equiv': '≅',
  'tilde.not': '≁',
  'tilde.nequiv': '≇',
  propto: '∝',
  'propto.var': '∝',
  perp: '⊥',
  parallel: '∥',
  'parallel.not': '∦',
  mid: '∣',
  'mid.not': '∤',

  // Relations - order
  'lt.eq': '≤',
  'gt.eq': '≥',
  'lt.eq.not': '≰',
  'gt.eq.not': '≱',
  'lt.not': '≮',
  'gt.not': '≯',
  'lt.tri': '⊲',
  'gt.tri': '⊳',
  'lt.tri.eq': '⊴',
  'gt.tri.eq': '⊵',
  prec: '≺',
  succ: '≻',
  'prec.eq': '≼',
  'succ.eq': '≽',
  'prec.not': '⊀',
  'succ.not': '⊁',
  'prec.equiv': '≾',
  'succ.equiv': '≿',
  ll: '≪',
  gg: '≫',
  'lt.double': '≪',
  'gt.double': '≫',

  // Arrows - rightward
  'arrow.r': '→',
  'arrow.r.long': '⟶',
  'arrow.r.double': '⇒',
  'arrow.r.long.double': '⟹',
  'arrow.r.triple': '⇛',
  'arrow.r.squiggly': '⟿',
  'arrow.r.hook': '↪',
  'arrow.r.bar': '↦',
  'arrow.r.tilde': '⇝',
  'arrow.r.not': '↛',
  'arrow.r.double.not': '⇏',
  'arrow.r.dashed': '⇢',
  'arrow.r.dotted': '⇠',
  'arrow.r.wave': '↜',
  'arrow.r.two': '⇉',
  'arrow.r.stop': '↣',
  'arrow.r.curve': '⤳',
  'arrow.r.loop': '↺',

  // Arrows - leftward
  'arrow.l': '←',
  'arrow.l.long': '⟵',
  'arrow.l.double': '⇐',
  'arrow.l.long.double': '⟸',
  'arrow.l.hook': '↩',
  'arrow.l.bar': '↤',
  'arrow.l.not': '↚',
  'arrow.l.double.not': '⇍',
  'arrow.l.dashed': '⇠',
  'arrow.l.two': '⇇',
  'arrow.l.stop': '↢',
  'arrow.l.curve': '⤶',

  // Arrows - bidirectional
  'arrow.l.r': '↔',
  'arrow.l.r.long': '⟷',
  'arrow.l.r.double': '⇔',
  'arrow.l.r.long.double': '⟺',
  'arrow.l.r.not': '↮',
  'arrow.l.r.double.not': '⇎',

  // Arrows - vertical
  'arrow.t': '↑',
  'arrow.b': '↓',
  'arrow.t.double': '⇑',
  'arrow.b.double': '⇓',
  'arrow.t.b': '↕',
  'arrow.t.b.double': '⇕',
  'arrow.t.l': '↖',
  'arrow.t.r': '↗',
  'arrow.b.l': '↙',
  'arrow.b.r': '↘',

  // Arrows - harpoons
  'harpoon.rt': '⇀',
  'harpoon.rb': '⇁',
  'harpoon.lt': '↼',
  'harpoon.lb': '↽',
  'harpoon.tl': '↿',
  'harpoon.tr': '↾',
  'harpoon.bl': '⇃',
  'harpoon.br': '⇂',

  // Big operators
  sum: '∑',
  product: '∏',
  coproduct: '∐',
  integral: '∫',
  'integral.double': '∬',
  'integral.triple': '∭',
  'integral.cont': '∮',
  'integral.cont.double': '∯',
  'integral.cont.triple': '∰',
  'integral.arrow.r': '∷',

  // Geometry / misc math
  degree: '°',
  angle: '∠',
  'angle.l': '⟨',
  'angle.r': '⟩',
  'angle.spheric': '∢',
  'angle.arc': '∡',

  // Dots
  'dots.h': '⋯',
  'dots.v': '⋮',
  'dots.d': '⋱',
  'dots.l': '⋰',
  'dots.c': '⋅',
  dots: '…',

  // Brackets / fences
  'floor.l': '⌊',
  'floor.r': '⌋',
  'ceil.l': '⌈',
  'ceil.r': '⌉',
  'bracket.l': '[',
  'bracket.r': ']',
  'bracket.double.l': '⟦',
  'bracket.double.r': '⟧',
  'brace.l': '{',
  'brace.r': '}',
  'paren.l': '(',
  'paren.r': ')',
  'bar.v': '|',
  'bar.v.double': '‖',

  // Miscellaneous
  aleph: 'ℵ',
  beth: 'ℶ',
  gimel: 'ℷ',
  daleth: 'ℸ',
  hbar: 'ℏ',
  planck: 'ℎ',
  ell: 'ℓ',
  Re: 'ℜ',
  Im: 'ℑ',
  wp: '℘',
  mho: '℧',
  weierp: '℘',
  laplace: '∆',
  gradient: '∇',
  sterling: '£',
  euro: '€',
  yen: '¥',
  cent: '¢',
  copyright: '©',
  trademark: '™',
  registered: '®',
  bullet: '•',
  section: '§',
  paragraph: '¶',
  lozenge: '◊',
  checkmark: '✓',
  'checkmark.light': '✔',
  cross: '✗',
  'cross.circle': '⊗',

  // Accents (returned as standalone characters for use with hat(), tilde() etc.)
  hat: '̂',
  bar: '̅',
  'tilde.accent': '̃',
  vec: '⃗',
  dot: '̇',
  'dot.double': '̈',
  acute: '́',
  grave: '̀',
  breve: '̆',
  macron: '̅',
  caron: '̌',
  circle: '̊',

  // Spacing (resolved to MathML/CSS spacing, not characters)
  thin: '',
  med: '',
  thick: '',
  quad: '',
  qquad: '',
  space: ' ',
  zws: '​',

  // Misc operators
  'plus.minus': '±',
  'minus.plus': '∓',
  'lt.eq.slant': '⩽',
  'gt.eq.slant': '⩾',
  wreath: '≀',
  multimap: '⊸',
  intercal: '⊺',
  bowtie: '⋈',
  ltimes: '⋉',
  rtimes: '⋊',
  divides: '∣',
  'divides.not': '∤',
  smash: '⨳',
  curlyeq: '≟',
  'sqrt.symbol': '√',
};

const SPACING_KINDS = new Set(['thin', 'med', 'thick', 'quad', 'qquad', 'space', 'zws']);

export function isSpacing(name: string): boolean {
  return SPACING_KINDS.has(name);
}

export function lookupSymbol(name: string): string | undefined {
  return SYMBOLS[name];
}
