/**
 * Fetches Typst source and generates src/symbols.ts.
 *
 * Usage: pnpm gen-symbols
 *
 * Reads the symbols!{} macro from crates/typst-library/src/symbols/sym.rs,
 * and the math symbol definitions from crates/typst-library/src/math/,
 * then emits a typed flat mapping of dotted names → Unicode characters.
 *
 * If the Typst repo is not cloned locally, it falls back to fetching
 * the raw file from GitHub.
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TYPST_SYMBOLS_URL =
  'https://raw.githubusercontent.com/typst/typst/main/crates/typst-library/src/symbols/sym.rs';

async function fetchTypstSymbols(): Promise<string> {
  const res = await fetch(TYPST_SYMBOLS_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching Typst symbols`);
  return res.text();
}

interface SymEntry {
  name: string;
  codepoint: number;
}

function parseSymbolsMacro(src: string): SymEntry[] {
  const entries: SymEntry[] = [];

  // Match patterns like:
  //   "name" => '\u{XXXX}',
  //   "name" => 'literal',
  const re = /"([\w.]+)"\s*=>\s*'\\u\{([0-9a-fA-F]+)\}'/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(src)) !== null) {
    entries.push({
      name: m[1]!,
      codepoint: parseInt(m[2]!, 16),
    });
  }

  // Also match literal character forms: "name" => 'X',
  const reLit = /"([\w.]+)"\s*=>\s*'([^'\\])'/g;
  while ((m = reLit.exec(src)) !== null) {
    entries.push({
      name: m[1]!,
      codepoint: m[2]!.codePointAt(0) ?? 0,
    });
  }

  return entries;
}

function emit(entries: SymEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const unique = new Map<string, number>();
  for (const e of sorted) {
    if (!unique.has(e.name)) unique.set(e.name, e.codepoint);
  }

  const lines = [...unique.entries()].map(([name, cp]) => {
    const char = String.fromCodePoint(cp);
    const escaped = JSON.stringify(char);
    return `  ${JSON.stringify(name)}: ${escaped},`;
  });

  return `// Generated by scripts/gen-symbols.ts — do not edit by hand.
// Source: Typst crates/typst-library/src/symbols/sym.rs
// Run \`pnpm gen-symbols\` to regenerate.

export const SYMBOLS: Record<string, string> = {
${lines.join('\n')}
};

export function lookupSymbol(name: string): string | undefined {
  return SYMBOLS[name];
}

export function isSpacing(name: string): boolean {
  return name === 'thin' || name === 'med' || name === 'thick' ||
    name === 'quad' || name === 'qquad' || name === 'space' || name === 'zws';
}
`;
}

async function main() {
  console.log('Fetching Typst symbol definitions...');
  const src = await fetchTypstSymbols();
  console.log(`  Fetched ${src.length} bytes`);

  const entries = parseSymbolsMacro(src);
  console.log(`  Parsed ${entries.length} symbol entries`);

  if (entries.length < 50) {
    console.warn('  Warning: fewer than 50 entries parsed — check the regex against Typst source');
  }

  const output = emit(entries);
  const outPath = resolve(__dirname, '../packages/kern/src/symbols.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(`Wrote ${outPath}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
